### ISSUE TITLE
add print view media query

### ISSUE THREAD

**Issue by jango-fx** [jango-fx/barebones-fx-hugo-theme#4]
```html
<head>
</head>
<body>
    …
    <link rel="stylesheet" type="text/css" href="print.css">
<body>
```

```css
@media print {
  header, footer, aside, form, … {
    display: none;
  }

  article {
    break-before: always;
    width:100%!important;
    padding:0!important;
    margin:0!important;
  }

  h1, h2, h3, h4, h5 {
    page-break-after: avoid;
  }

/*  a:after { content: "( " attr(href) ") ";} */
}

@page {
  size: landscape;
  margin: 2cm;


    counter-increment: page;
    counter-reset: page 1;
    @bottom-right {
      content: counter(page) " of " counter(pages);
  }
}
```
